name: Build Docker Image and Push to Dockerhub

# Controls when the action will run.
# Every time something is merged to master, the image will be rebuilt and pushed.
on:
  push:
    branches: [ master, jaclyn-taroni/build-and-push ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Login to Dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # set up Docker build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v2.2.2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: ccdl/training_dev:latest

      # If we have a failure, Slack us
      - name: Report failure to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@v1.1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }} 
          SLACK_MESSAGE: 'Training build Docker & push workflow failed'
