name: Build Docker

# Controls when the action will run. Triggers the workflow for a pull request for
# master when the Dockerfile or renv.lock file changes.
on:
  pull_request:
    branches: [ master ]
    paths: [ Dockerfile, renv.lock ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # set up Docker build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # setup layer cache
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Build docker image
      - name: Build Docker image
        uses: docker/build-push-action@v2.2.2
        with:
          push: false
          context: docker
          file: Dockerfile
          tags: ccdl/training_dev:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      # If we have a failure, Slack us
      - name: Report failure to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@v1.1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }} 
          SLACK_MESSAGE: 'Training Build Docker workflow failed'
